export const colors = [
  { name: "Red", hexCode: "#FF0000" },
  { name: "Green", hexCode: "#00FF00" },
  { name: "Blue", hexCode: "#0000FF" },
  { name: "Yellow", hexCode: "#FFFF00" },
  { name: "Cyan", hexCode: "#00FFFF" },
  { name: "Magenta", hexCode: "#FF00FF" },
  { name: "Black", hexCode: "#000000" },
  { name: "White", hexCode: "#FFFFFF" },
  { name: "Gray", hexCode: "#808080" },
  { name: "Brown", hexCode: "#A52A2A" },
  { name: "Orange", hexCode: "#FFA500" },
  { name: "Purple", hexCode: "#800080" },
  { name: "Pink", hexCode: "#FFC0CB" },
  { name: "Lime", hexCode: "#00FF00" },
  { name: "Teal", hexCode: "#008080" },
  { name: "Lavender", hexCode: "#E6E6FA" },
  { name: "Maroon", hexCode: "#800000" },
  { name: "Navy", hexCode: "#000080" },
  { name: "Olive", hexCode: "#808000" },
  { name: "Silver", hexCode: "#C0C0C0" },
  { name: " Blue", hexCode: "#87CEEB" },
  { name: "Indigo", hexCode: "#4B2" },
  { name: "Turquoise", hexCode: "#40E0D0" },
  { name: "Beige", hexCode: "#F5F5DC" },
  { name: "Salmon", hexCode: "#FA8072" },
  { name: "Gold", hexCode: "#FFD700" },
  { name: "Violet", hexCode: "#EE82EE" },
  { name: "Coral", hexCode: "#FF7F50" },
  { name: "Khaki", hexCode: "#F0E68C" },
  { name: "Plum", hexCode: "#DDA0DD" },
];
